{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.targetSecretName }}
  labels:
    {{- include "upgrade-lab.labels" . | nindent 4 }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.targetSecretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_DSN
      remoteRef:
        key: {{ .Values.externalSecrets.keys.postgresDsn }}
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.keys.sqlServerJdbcUrl }}
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.keys.sqlServerUsername }}
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.keys.sqlServerPassword }}
    - secretKey: REDIS_URL
      remoteRef:
        key: {{ .Values.externalSecrets.keys.redisUrl }}
    - secretKey: MONGO_URI
      remoteRef:
        key: {{ .Values.externalSecrets.keys.cosmosMongoUri }}
    - secretKey: client-certificate.pfx
      remoteRef:
        key: {{ .Values.externalSecrets.keys.clientCertificate }}
{{- end }}
