{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "upgrade-lab.fullname" $ }}-{{ $name }}
  labels:
    {{- include "upgrade-lab.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "upgrade-lab.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
{{- end }}
