replicaCount: 2

image:
  repository: ghcr.io/ihsenalaya/kubeupgrade-guardian-operator
  tag: "0.1.3"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations:
  kubectl.kubernetes.io/default-container: manager
podLabels: {}

leaderElection:
  enabled: true

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1

serviceMonitor:
  enabled: false
  labels: {}
  interval: "30s"

priorityClassName: ""

terminationGracePeriodSeconds: 10
