/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// AssessmentMode controls whether the controller may do anything beyond read-only assessment.
// +kubebuilder:validation:Enum=ReadOnly
type AssessmentMode string

const (
	// AssessmentModeReadOnly is the only supported mode. It forbids upgrade, drain, or workload mutation actions.
	AssessmentModeReadOnly AssessmentMode = "ReadOnly"
)

// AssessmentProfile tunes how non-universal findings are interpreted.
// +kubebuilder:validation:Enum=lab;staging;production
type AssessmentProfile string

const (
	AssessmentProfileLab        AssessmentProfile = "lab"
	AssessmentProfileStaging    AssessmentProfile = "staging"
	AssessmentProfileProduction AssessmentProfile = "production"
)

// AssessmentPhase describes the observed lifecycle of an assessment.
// +kubebuilder:validation:Enum=Pending;Running;Completed;Failed
type AssessmentPhase string

const (
	AssessmentPhasePending   AssessmentPhase = "Pending"
	AssessmentPhaseRunning   AssessmentPhase = "Running"
	AssessmentPhaseCompleted AssessmentPhase = "Completed"
	AssessmentPhaseFailed    AssessmentPhase = "Failed"
)

// RiskLevel is the severity of a finding or the aggregate assessment risk.
// +kubebuilder:validation:Enum=Critical;High;Medium;Low;Info
type RiskLevel string

const (
	RiskLevelCritical RiskLevel = "Critical"
	RiskLevelHigh     RiskLevel = "High"
	RiskLevelMedium   RiskLevel = "Medium"
	RiskLevelLow      RiskLevel = "Low"
	RiskLevelInfo     RiskLevel = "Info"
)

// Decision is the non-executing upgrade recommendation generated by the assessment.
// +kubebuilder:validation:Enum=Proceed;ProceedWithCaution;DoNotUpgrade;AssessmentIncomplete
type Decision string

const (
	DecisionProceed              Decision = "Proceed"
	DecisionProceedWithCaution   Decision = "ProceedWithCaution"
	DecisionDoNotUpgrade         Decision = "DoNotUpgrade"
	DecisionAssessmentIncomplete Decision = "AssessmentIncomplete"
)

// FindingClassificationStatus states how a finding is used for decisioning.
// +kubebuilder:validation:Enum=Blocking;AcceptedRisk;ProviderManaged;Informational
type FindingClassificationStatus string

const (
	FindingClassificationBlocking        FindingClassificationStatus = "Blocking"
	FindingClassificationAcceptedRisk    FindingClassificationStatus = "AcceptedRisk"
	FindingClassificationProviderManaged FindingClassificationStatus = "ProviderManaged"
	FindingClassificationInformational   FindingClassificationStatus = "Informational"
)

const (
	FindingTypeRBACAssessmentGap       = "RBAC_ASSESSMENT_GAP"
	FindingTypeWorkloadAvailability    = "WORKLOAD_AVAILABILITY_RISK"
	FindingTypeMissingReadinessProbe   = "MISSING_READINESS_PROBE"
	FindingTypePDBBlockingRisk         = "PDB_BLOCKING_RISK"
	FindingTypeAdmissionWebhookRisk    = "ADMISSION_WEBHOOK_RISK"
	FindingTypePolicyRisk              = "POLICY_RISK"
	FindingTypeDeprecatedOrRemovedAPI  = "DEPRECATED_OR_REMOVED_API"
	FindingTypeCapacityDrainRisk       = "CAPACITY_DRAIN_RISK"
	FindingTypeObservabilityGap        = "OBSERVABILITY_GAP"
	FindingTypePolicyEngineDetected    = "POLICY_ENGINE_DETECTED"
	FindingTypeObservabilityCapability = "OBSERVABILITY_CAPABILITY_DETECTED"
)

// ResourceRef identifies a Kubernetes resource used as finding evidence.
type ResourceRef struct {
	APIVersion string `json:"apiVersion,omitempty"`
	Kind       string `json:"kind,omitempty"`
	Namespace  string `json:"namespace,omitempty"`
	Name       string `json:"name,omitempty"`
}

// FindingClassification records the rule that determined whether a finding is blocking.
type FindingClassification struct {
	Status      FindingClassificationStatus `json:"status"`
	Reason      string                      `json:"reason,omitempty"`
	MatchedRule string                      `json:"matchedRule,omitempty"`
}

// Evidence is an observable fact collected from the cluster.
type Evidence struct {
	ID          string            `json:"id"`
	Description string            `json:"description"`
	Resource    *ResourceRef      `json:"resource,omitempty"`
	Observed    map[string]string `json:"observed,omitempty"`
}

// Finding is a risk or an assessment gap backed by observable evidence.
type Finding struct {
	ID             string                 `json:"id"`
	Type           string                 `json:"type"`
	Severity       RiskLevel              `json:"severity"`
	Category       string                 `json:"category"`
	Resource       *ResourceRef           `json:"resource,omitempty"`
	Message        string                 `json:"message"`
	Evidence       []Evidence             `json:"evidence,omitempty"`
	Recommendation string                 `json:"recommendation,omitempty"`
	Classification *FindingClassification `json:"classification,omitempty"`
}

// RequiredAction is a recommended non-mutating remediation step in an UpgradePlan.
type RequiredAction struct {
	ID           string      `json:"id"`
	Severity     RiskLevel   `json:"severity"`
	Category     string      `json:"category"`
	Resource     ResourceRef `json:"resource,omitempty"`
	Action       string      `json:"action"`
	EvidenceRefs []string    `json:"evidenceRefs,omitempty"`
}

// ClassifiedFindingRef is a compact finding reference published in an UpgradePlan.
type ClassifiedFindingRef struct {
	ID             string                `json:"id"`
	Type           string                `json:"type,omitempty"`
	Severity       RiskLevel             `json:"severity,omitempty"`
	Category       string                `json:"category,omitempty"`
	Resource       ResourceRef           `json:"resource,omitempty"`
	Message        string                `json:"message,omitempty"`
	Recommendation string                `json:"recommendation,omitempty"`
	Classification FindingClassification `json:"classification"`
}

// AssessmentReference points an UpgradePlan back to its source UpgradeAssessment.
type AssessmentReference struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
}

// PlanReference points an UpgradeAssessment status to the generated UpgradePlan.
type PlanReference struct {
	Name string `json:"name"`
}

// ArtifactReference points an UpgradeAssessment status to the generated human-readable artifact.
type ArtifactReference struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
	Kind      string `json:"kind,omitempty"`
}

// FindingSummary stores aggregate finding counts.
type FindingSummary struct {
	TotalFindings int `json:"totalFindings"`
	Critical      int `json:"critical"`
	High          int `json:"high"`
	Medium        int `json:"medium"`
	Low           int `json:"low"`
	Info          int `json:"info,omitempty"`
}

// ClassificationSummary stores aggregate counts by finding classification.
type ClassificationSummary struct {
	Total           int `json:"total"`
	Blocking        int `json:"blocking"`
	AcceptedRisk    int `json:"acceptedRisk,omitempty"`
	ProviderManaged int `json:"providerManaged,omitempty"`
	Informational   int `json:"informational,omitempty"`
}

// UpgradePhase describes a non-executing step in the recommended upgrade chronology.
type UpgradePhase struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

// UpgradePathStep describes one Kubernetes minor-version hop.
type UpgradePathStep struct {
	From   string         `json:"from"`
	To     string         `json:"to"`
	Phases []UpgradePhase `json:"phases,omitempty"`
}

// Condition helpers.
const (
	ConditionAssessmentRunning   = "AssessmentRunning"
	ConditionAssessmentCompleted = "AssessmentCompleted"
	ConditionAssessmentFailed    = "AssessmentFailed"
)

// Now returns a metav1.Time. Keeping this tiny helper in the API package avoids
// tests depending on wall-clock formatting details.
func Now() metav1.Time {
	return metav1.Now()
}
